
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

  ai-planner:
    build: ./ai_planner
    container_name: ai-planner
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped
